CREATE DATABASE "volgintest11"
GO
USE "volgintest11"
CREATE TABLE "DOLSHNOSTI"
("ID" INT IDENTITY ,
"NAME" varchar(50)PRIMARY KEY,
"OKLAD" MONEY NOT NULL)
GO
CREATE TABLE "SOTRUDNIKI"
("ID" INT IDENTITY ,
"FIO" varchar(50)PRIMARY KEY,
"ZP" MONEY NOT NULL,
"DOLSHNOST'" VARCHAR(50)NOT NULL);
GO
CREATE TABLE "OTDELS"
("ID" INT IDENTITY ,
"NAZVANIE" varchar(50)PRIMARY KEY,
"MAIN" varchar(50)NOT NULL)
GO
CREATE TABLE "Sklad"
("ID" INT IDENTITY PRIMARY KEY,
"TOVAR" varchar(50)unique,
"PRICE" MONEY NOT NULL,
"OTDEL" varchar(50)NOT NULL ,
"KOL-VO" INT NOT NULL)


